# Generated by Django 2.2 on 2019-04-11 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indy_community', '0005_auto_20190409_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('consent_enablement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_enablement', to='indy_community.AgentConversation')),
                ('imms_consent_proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imms_consent_proof', to='indy_community.AgentConversation')),
                ('imms_status_proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imms_status_proof', to='indy_community.AgentConversation')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndyWallet', to_field='wallet_name')),
                ('wallet_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndyOrgRole')),
            ],
        ),
    ]
