# Generated by Django 2.2 on 2019-04-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indy_community', '0005_auto_20190409_0051'),
        ('imms_demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=120)),
                ('birth_date', models.DateField()),
                ('health_id_type', models.CharField(max_length=20)),
                ('parent_health_id', models.CharField(blank=True, max_length=20, null=True)),
                ('issue_date', models.DateField()),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndyWallet', to_field='wallet_name')),
                ('last_issued', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_id_issued', to='indy_community.AgentConversation')),
            ],
        ),
        migrations.CreateModel(
            name='ImmunizationStatusCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immunization_status', models.CharField(max_length=20)),
                ('immunization_status_date', models.DateField()),
                ('issue_date', models.DateField()),
                ('health_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imms_status_certificate', to='imms_demo.HealthIdentity', to_field='health_id')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndyWallet', to_field='wallet_name')),
                ('last_issued', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imms_status_issued', to='indy_community.AgentConversation')),
            ],
        ),
    ]
