# Generated by Django 2.2 on 2019-04-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indy_community', '0007_auto_20190413_0125'),
        ('imms_demo', '0002_healthidentity_immunizationstatuscertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationconversation',
            name='health_id_proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_id_proof', to='indy_community.AgentConversation'),
        ),
        migrations.AddField(
            model_name='immunizationconversation',
            name='initiation_date',
            field=models.DateField(default='2019-04-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='immunizationconversation',
            name='consent_enablement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_enablement', to='indy_community.AgentConversation'),
        ),
        migrations.AlterField(
            model_name='immunizationconversation',
            name='imms_consent_proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imms_consent_proof', to='indy_community.AgentConversation'),
        ),
        migrations.AlterField(
            model_name='immunizationconversation',
            name='imms_status_proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imms_status_proof', to='indy_community.AgentConversation'),
        ),
    ]
