# Generated by Django 2.2 on 2019-04-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imms_demo', '0003_auto_20190413_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationconversation',
            name='msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
