# Generated by Django 2.2 on 2019-04-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indy_community', '0007_auto_20190413_0125'),
        ('imms_demo', '0004_immunizationconversation_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoImmunizationConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_id', models.CharField(blank=True, max_length=20, null=True)),
                ('consenting_health_id', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(max_length=20)),
                ('msg', models.CharField(blank=True, max_length=200, null=True)),
                ('initiation_date', models.DateField()),
                ('imms_consent_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imms_consent_request', to='indy_community.AgentConversation')),
                ('imms_status_proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imms_status_proof', to='indy_community.AgentConversation')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndyWallet', to_field='wallet_name')),
                ('wallet_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndyOrgRole')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolImmunizationConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=80)),
                ('first_name_parent', models.CharField(max_length=60)),
                ('last_name_parent', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=20)),
                ('msg', models.CharField(blank=True, max_length=200, null=True)),
                ('initiation_date', models.DateField()),
                ('consent_enablement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_enablement', to='indy_community.AgentConversation')),
                ('health_id_proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_id_proof', to='indy_community.AgentConversation')),
                ('imms_status_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imms_status_request', to='indy_community.AgentConversation')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndyWallet', to_field='wallet_name')),
                ('wallet_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndyOrgRole')),
            ],
        ),
        migrations.DeleteModel(
            name='ImmunizationConversation',
        ),
    ]
